{% set name = "stempeg" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a09c8de50f218c8d5e32fca3ecf59d2c1a27430fea1e20340c7f0468a240c82

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ffmpeg
    - setuptools
    - numpy >=1.6
    - pysoundfile >=0.9.0

test:
  imports:
    - stempeg

about:
  home: https://github.com/faroit/stempeg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python tool to read and write STEM files
  doc_url: https://github.com/faroit/stempeg
  dev_url: https://github.com/faroit/stempeg

extra:
  recipe-maintainers:
    - Faylixe
