{% set name = "stempeg" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e587007187f05215e50d92a693f2ca0d84aef6f45ae6212f85d5a8455f7b2bb1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ffmpeg
    - setuptools
    - numpy >=1.6
    - pysoundfile >=0.9.0

test:
  imports:
    - stempeg

about:
  home: https://github.com/faroit/stempeg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python tool to read and write STEM files'
  doc_url: https://github.com/faroit/stempeg
  dev_url: https://github.com/faroit/stempeg

extra:
  recipe-maintainers:
    - Faylixe
